### ISSUE TITLE
Ruby version not set on first compile

### ISSUE THREAD

**Issue by balrogboogie** [oxidize-rb/rb-sys#189]
I've set a project up according to the docs here, but when I run `rake compile` the first time, I get this error:

```
$ rake compile
cd tmp/x86_64-darwin22/mygem/3.2.1
/Users/me/.rvm/rubies/ruby-3.2.1/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/mygem/extconf.rb
cd -
cd tmp/x86_64-darwin22/mygem/3.2.1
/usr/bin/make
generating /Users/me/Code/mygem/target/release/libmygem.dylib (release)

// SNIP ....

error: failed to run custom build command for `mygem v0.1.14 (/Users/me/Code/mygem/ext/mygem)`

Caused by:
  process didn't exit successfully: `/Users/me/Code/mygem/target/release/build/mygem-d7552165fcd432a6/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rb-sys-env-0.1.2/src/ruby_version.rs:128:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [/Users/me/Code/mygem/target/release/libmygem.dylib] Error 101
rake aborted!
Command failed with status (2): [/usr/bin/make...]
/Users/me/.rvm/gems/ruby-3.2.1/gems/rake-compiler-1.2.1/lib/rake/extensiontask.rb:181:in `block (2 levels) in define_compile_tasks'
/Users/me/.rvm/gems/ruby-3.2.1/gems/rake-compiler-1.2.1/lib/rake/extensiontask.rb:180:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-darwin22 => compile:mygem:x86_64-darwin22 => copy:mygem:x86_64-darwin22:3.2.1 => tmp/x86_64-darwin22/mygem/3.2.1/mygem.bundle
(See full trace by running task with --trace)
```

If I instead run this:

```
$ DEP_RB_MAJOR=3 DEP_RB_MINOR=2 DEP_RB_TEENY=1 rake compile
```

then it works, and subsequent builds work without needing to set those environment variables as long as I keep the `target` directory around.

I don't see any docs about setting those env vars, which makes me think I shouldn't have to do this, am I doing something wrong here?

**Comment by ianks** [comment]
Those env vars are setup by `rb-sys-env`. It's needed when you want to run `cargo test`, and generally shouldn't impact `rake-compiler-dock` builds. Can you point me to the docs you used?

### Fixes

1. In general, the best way to start a new gem is to use bundler now:

```
$ gem update --system
$ bundle gem --ext=rust mygem
```

2. In your particular case, I think adding a `build.rs` file with the below will fix things:


```
// build.rs

fn main() -> Result<(), Box<dyn std::error::Error>> {
  let _ = rb_sys_env::activate()?;
  Ok(())
}
```

**Comment by balrogboogie** [comment]
I'm trying to convert a rutie project over to use magnus instead, so my gem layout might not be exactly the same, but I tried to get all the pieces into place. I already have the build.rs with those contents, that's where the error is coming from: 

```
Caused by:
  process didn't exit successfully: `/Users/me/Code/was/mygem/target/release/build/mygem-d7552165fcd432a6/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rb-sys-env-0.1.2/src/ruby_version.rs:128:18
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
     2: core::panicking::panic
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
     3: core::option::Option<T>::unwrap
     4: rb_sys_env::ruby_version::verpart
     5: rb_sys_env::ruby_version::RubyVersion::from_raw_environment
     6: rb_sys_env::rb_env::RbEnv::ruby_version
     7: rb_sys_env::rb_env::RbEnv::print_cargo_rustc_cfg
     8: rb_sys_env::activate
     9: build_script_build::main
    10: core::ops::function::FnOnce::call_once
```

**Comment by ianks** [comment]
Do you have `rb-sys` listed as a dependency in `Cargo.toml`? That is required for `rb-sys-env` to work

**Comment by balrogboogie** [comment]
Yep, that did fix it. I'm curious why, though, since I did have magnus with `features = "rb-sys-interop"`, and that was pulling rb-sys in.

**Comment by ianks** [comment]
Sorry for the late reply, wrote a response earlier but forgot to click the  green button 😨 

> Yep, that did fix it. I'm curious why, though, since I did have magnus with features = ["rb-sys-interop"], and that was pulling rb-sys in. Adding rb-sys to the Cargo.toml changed nothing about the Cargo.lock so I guess I'm just surprised it made a difference

Essentially, it comes down to how Cargo propogates configuration via the [`links` manifest key](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key). In order for a crate to receive the `DEP_RB_*` configuration options needed for rb-sys-env to work in a `build.rs`, the crate has to have a direct dependency on `rb-sys`. Hopefully that makes sense
