### ISSUE TITLE
Incorrect linker being chosen for aarch64-linux

### ISSUE THREAD

**Issue by gjtorikian** [oxidize-rb/rb-sys#193]
For repro steps: go ahead and `git clone https://github.com/gjtorikian/what_you_say.git`. 

Then, run `rb-sys-dock --platform aarch64-linux --build `.

You'll see a rather long error message -- I've snipped out the relevant bits:

```
/usr/local/cargo/bin/cargo rustc  --manifest-path /Users/gjtorikian/Development/yettoapp/what_you_say/ext/what_you_say/Cargo.toml --target aarch64-unknown-linux-gnu --target-dir /Users/gjtorikian/Development/yettoapp/what_you_say/tmp/rb-sys-dock/aarch64-linux/target --lib --release -- -C linker=aarch64-linux-gnu-gcc -L native=/usr/local/rake-compiler/ruby/aarch64-linux-gnu/ruby-3.2.0/lib -C link-arg=-pipe -C link-arg=-lm -l pthread

....

 = note: /usr/bin/ld: /Users/gjtorikian/Development/yettoapp/what_you_say/tmp/rb-sys-dock/aarch64-linux/target/aarch64-unknown-linux-gnu/release/deps/lingua-f82a953811617e50.lingua.232da8fb-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
         /usr/bin/ld: /Users/gjtorikian/Development/yettoapp/what_you_say/tmp/rb-sys-dock/aarch64-linux/target/aarch64-unknown-linux-gnu/release/deps/lingua-f82a953811617e50.lingua.232da8fb-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)

```

Debugging this error lead me to understand that I'm using the wrong linker. However, while the `rb-sys-dock` build command clearly says `-C linker=aarch64-linux-gnu-gcc`; the error message states that the linker is `/usr/bin/ld`.

I wasn't able to set `.cargo/config.toml` to fix this, unfortunately:

```toml
[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=/usr/bin/aarch64-linux-gnu-gcc",
]
```

I was only able to get the build to complete succesfully by logging into the Docker container and then setting the `RUSTFLAGS` env var:

```
rb-sys-dock --platform aarch64-linux  
RUSTFLAGS="-C linker=/usr/bin/aarch64-linux-gnu-gcc" rake native:aarch64-linux gem 
```

I'm not sure if the correct linker isn't being used because the full path isn't being provided or what, but it certainly seems to be an error in how the command is prepared for this platform.

**Comment by ianks** [comment]
Thanks for the report, may need to set `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER="/usr/bin/aarch64-linux-gnu-gcc"` in the Dockerfile. Does that flag work for you when running locally?

**Comment by ianks** [comment]
Ok that env seems to fix it for me, going to push up a commit
