### ISSUE TITLE
still not working on windows for me

### ISSUE THREAD

**Issue by dsisnero** [oxidize-rb/rb-sys#216]
I tried gem install polars-df which uses rb-sys by directly calling it (no ridk enable).
[gem install polars-df 2>&1](https://gist.github.com/dsisnero/2dd338eb4f169ba9243900de8fabe0f6)

After ridk enable
[ridk enable - gem install polars-df 2>1](https://gist.github.com/dsisnero/6c67f3f9ec3391e5768fc3bff784e1f2)

[gem env (after ridk enable)](https://gist.github.com/dsisnero/d14a86afdacdc9c9bc305797427cbcb4)

**Comment by ianks** [comment]
Can you try the latest version? v0.9.77 had fixes for clang16

**Comment by tisonkun** [comment]
> Can you try the latest version? v0.9.77 had fixes for clang16

At least it seems to fix an issue on Apple M1. See https://github.com/apache/incubator-opendal/pull/2451.

**Comment by Speak2Erase** [comment]
This is still an issue for me when compiling any of my projects using ruby 3.2.2 on windows.
[compile.txt](https://github.com/oxidize-rb/rb-sys/files/12068541/compile.txt)

**Comment by Speak2Erase** [comment]
This seems to be related: https://github.com/rust-lang/rust-bindgen/issues/2500

**Comment by ianks** [comment]
what version of libclang are you using?

**Comment by Speak2Erase** [comment]
16

**Comment by ianks** [comment]
Currently clang-16 seems to be buggy for windows users with rb-sys, and [we only test against clang-15](https://github.com/oxidize-rb/actions/blob/afa47539da39b0748cb79eb9c3328688da45ae8c/setup-ruby-and-rust/action.yml#L74) right now. Hopefully that will change when we upgrade bindgen next, but hands are a bit tied because that affects our MSRV policy.

Can you try out clang-15?

**Comment by Speak2Erase** [comment]
Yup, after some messing around with msys2 packages, that worked!

**Comment by dsisnero** [comment]
how did you try this with clang-15 ?  did you install with pacman?

**Comment by ianks** [comment]
Closing in favor of #286

**Comment by stanhu** [comment]
I see the build trace in https://gist.github.com/dsisnero/2dd338eb4f169ba9243900de8fabe0f6 shows:

```
  thread 'main' panicked at 'Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))', F:\windows\tools\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.60.1\src\ir\context.rs:1975:26
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

That there is a workaround mentioned in https://github.com/rust-lang/rust-bindgen/issues/2500#issuecomment-1640545912, which we implemented in https://github.com/oxidize-rb/actions/pull/55. We should probably document this.
