### ISSUE TITLE
Automation for `rake-compiler-dock` releases?

### ISSUE THREAD

**Issue by gjtorikian** [oxidize-rb/rb-sys#308]
I really hate the fact that Ruby major versions release on Dec 25. It's always a PITA for maintainers of gems, and every year, even though I prepare to cut a few new gems, I get caught off guard with a new surprising issue.

I was thinking about how to reduce human involvement to prevent something like https://github.com/oxidize-rb/rb-sys/pull/298 happening again. Let me reiterate that I don't think this dependency update not being released was anyone's "fault," at all; this is not a postmortem or anything of the sort! But I want to strengthen the gem ecosystem by minimizing rote tasks like updating the version number in various Dockerfiles. `rb-sys` now has various downstream consumers, and, selfishly, I am one of them.

With that I propose:

1. A GitHub action that runs on a daily cron, to
2. Check to see if there's a new `rake-compiler -dock` release, and if so
3. Open a PR which changes all the necessary Dockerfiles to match the `M.m.p` version

Happy to do the work to do this if it's desired! Just throwing the idea out there. ☮️  This of course won't solve the issue entirely—the new builds still need to be pushed—but it's a start.

**Comment by ianks** [comment]
Yeah I'm definitely game for this 👍🏻

**Comment by gjtorikian** [comment]
Given https://github.com/oxidize-rb/rb-sys/pull/469 it looks like Dependabot handles this these days
