### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by fpacanowski** [oxidize-rb/rb-sys#314]
I'm benchmarking different ways of creating a large nested hash in Ruby. I have tried 4 different implementations:
- Plain Ruby
- C extension
- Rust extension using `rb-sys`
- Rust extension using `magnus`

My results:
```
Calculating -------------------------------------
          Plain Ruby    229.184  (± 5.2%) i/s -      1.150k in   5.036150s
         C extension    327.014  (± 2.8%) i/s -      1.643k in   5.027833s
    rb-sys extension    157.108  (± 1.9%) i/s -    795.000  in   5.062144s
    Magnus extension    117.181  (± 3.4%) i/s -    594.000  in   5.073691s

Comparison:
         C extension:      327.0 i/s
          Plain Ruby:      229.2 i/s - 1.43x  slower
    rb-sys extension:      157.1 i/s - 2.08x  slower
    Magnus extension:      117.2 i/s - 2.79x  slower
```

Unsurprisingly, C extension is faster than plain Ruby. But it turns out that Rust extension is 2x _slower_ than C extension. Could you provide some insight as to why this is the case? I expected Rust extension to be on par with C extension.

I attach the relevant code below. You can also see my whole setup in [this repo](https://github.com/fpacanowski/ruby-extensions-benchmark/tree/44158c8247f876ebc3d57ed60614358e40a5d61a).

<details>
<summary>Code</summary>

**Ruby:**
```ruby
PAYLOAD = "ABC"*100

def build_tree(depth)
  if depth == 1
    return {label: PAYLOAD.dup , children: []}
  end
  return {label: PAYLOAD.dup, children: [build_tree(depth-1), build_tree(depth-1)]}
end

def build_big_tree
  build_tree(13)
end
```

**C extension:**
```c
char PAYLOAD[] = "ABC(...)";

VALUE rb_mCext;

VALUE build_tree(int depth) {
  VALUE result = rb_hash_new();
  VALUE children = rb_ary_new();
  if(depth != 1) {
    rb_ary_push(children, build_tree(depth-1));
    rb_ary_push(children, build_tree(depth-1));
  }
  rb_hash_aset(result, ID2SYM(rb_intern("label")), rb_str_new_cstr(PAYLOAD));
  rb_hash_aset(result, ID2SYM(rb_intern("children")), children);
  return result;
}

VALUE build_big_tree() {
  return build_tree(13);
}
```

**Rust extension:**
```rust
static PAYLOAD: &str = "ABC(...)";

unsafe fn build_tree(depth: i32) -> VALUE {
    let result = rb_hash_new();
    let children = rb_ary_new();
    if depth != 1 {
        rb_ary_push(children, build_tree(depth - 1));
        rb_ary_push(children, build_tree(depth - 1));
    }
    rb_hash_aset(
        result,
        rb_id2sym(rb_intern("label".to_cstring())),
        rb_str_new_cstr(PAYLOAD.to_cstring()),
    );
    rb_hash_aset(
        result,
        rb_id2sym(rb_intern("children".to_cstring())),
        children,
    );
    return result;
}

unsafe extern "C" fn build_big_tree(_: VALUE) -> VALUE {
    return build_tree(13);
}
```
</details>

**Comment by ianks** [comment]
Just had some time to look into this, and there are two main reasons:

1. Using `CString` will cause a memory allocation that unnecessary. Switching to static pointers (i.e. `"some-static-string\0".as_ptr()`) helps a lot
2. Even after the above change, I noticed that `rb-sys` was still slower for some reason. Turns out, [`symbol.h` provides an static, inline-able bit of C code](https://github.com/ruby/ruby/blob/42177a8987c06678f0afed713457fa327d606c62/include/ruby/internal/symbol.h#L290) that C extensions are able to use for `rb_intern`. Not a huge deal, it's easy to memoize.

With these two changes:

```
Calculating -------------------------------------
          Plain Ruby    476.459  (± 3.6%) i/s -      2.405k in   5.054495s
    rb-sys extension    584.625  (± 6.0%) i/s -      2.990k in   5.134537s
         C extension    517.207  (± 7.5%) i/s -      2.596k in   5.052228s
    Magnus extension    278.672  (± 6.5%) i/s -      1.400k in   5.048689s

Comparison:
    rb-sys extension:      584.6 i/s
         C extension:      517.2 i/s - same-ish: difference falls within error
          Plain Ruby:      476.5 i/s - 1.23x  slower
    Magnus extension:      278.7 i/s - 2.10x  slower

Plain Ruby = 2.10 ms
rb-sys extension = 1.72 ms
C extension = 1.95 ms
Magnus extension = 3.61 ms
```

You can see my changes here: https://github.com/fpacanowski/ruby-extensions-benchmark/compare/master...ianks:ruby-extensions-benchmark:rb-sys-opt

**Comment by fpacanowski** [comment]
Thank you for the thorough answer!

**Comment by ianks** [comment]
> @ianks One more thought. I based my code on [oxi-test example](https://github.com/oxidize-rb/oxi-test/blob/main/ext/src/lib.rs). Do you think it makes sense to make the example more performant or add a note about unnecessary allocation?

definitely. i would for sure merge a PR for that!
