### ISSUE TITLE
0.9.87 tag doesn't exist in rbsys/x86_64-linux-musl docker 

### ISSUE THREAD

**Issue by IAPark** [oxidize-rb/rb-sys#324]
I'm getting errors like this

```
Error response from daemon: manifest for rbsys/x86_64-linux-musl:0.9.87 not found: manifest unknown: manifest unknown
Error: ❌ Error running command: $ ["/usr/bin/docker pull rbsys/x86_64-linux-musl:0.9.87 --platform linux/amd64 --quiet > /dev/null"]
Error: Process completed with exit code 1.
```

I'm not sure if this is properly an issue with this repo or the https://github.com/oxidize-rb/actions repo as it's related to the `oxidize-rb/actions/cross-gem@v1` github action

**Comment by andreaslillebo** [comment]
If I check Docker Hub, the `0.9.87`-tag is missing for `rbsys/x86_64-linux-musl`:
https://hub.docker.com/r/rbsys/x86_64-linux-musl/tags

This does not appear to be an issue for other systems, e.g. [arm64-darwin](https://hub.docker.com/layers/rbsys/arm64-darwin/0.9.87/images/sha256-8657ba90485ff65349e68dde47a2e1ed6666e598b25d4ed4aba88ee21c31fe75?context=explore).

**Comment by ianks** [comment]
Weird... it looks like the build completed: https://github.com/oxidize-rb/rb-sys/actions/runs/7595777116/job/20688717806

**Comment by ianks** [comment]
I was looking at the wrong build (for `main` instead of the `v0.9.87` tag). I [just triggered a re-build](https://github.com/oxidize-rb/rb-sys/actions/runs/7595777108), hopefully this fixes it.

**Comment by ianks** [comment]
Ok that worked!
