### ISSUE TITLE
Use stable_abi/compiled.{c,rs} on non-CRuby

### ISSUE THREAD

**Issue by eregon** [oxidize-rb/rb-sys#424]
Hello,

I'm coming from https://github.com/oracle/truffleruby/issues/3396, in short we're trying to make Rust extensions work on TruffleRuby.
There were some minor fixes in RbConfig, etc which have been fixed in truffleruby-dev.

The remaining errors are in https://github.com/oracle/truffleruby/issues/3396#issuecomment-2356400143
So for example:
```
error[E0609]: no field `flags` on type `uncategorized::RBasic`
  --> /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/commonmarker-1.1.5/ext/commonmarker/.rb-sys/stable/cargo/registry/src/index.crates.io-6f17d22bba15001f/rb-sys-0.9.99/src/stable_api/ruby_3_2.rs:19:35
   |
19 |         let flags = rstring.basic.flags;
   |                                   ^^^^^ unknown field
```

This is because TruffleRuby [doesn't and cannot](https://github.com/oracle/truffleruby/issues/3118) expose `flags` on `struct RBasic`.
And anyway we can see the code in ruby_3_2.rs is highly CRuby-specific:
https://github.com/oxidize-rb/rb-sys/blob/991df6de21d244631e1b889070a8e4136f4220fe/crates/rb-sys/src/stable_api/ruby_3_2.rs#L19-L26

So such code in this file should only be used on CRuby, and on no other Ruby implementation.
And https://github.com/oxidize-rb/rb-sys/blob/991df6de21d244631e1b889070a8e4136f4220fe/crates/rb-sys/src/stable_api/compiled.c should be used instead.
A good way to test if it's CRuby is `RUBY_ENGINE == "ruby"`.

Could you fix this issue?

Related: https://github.com/oxidize-rb/rb-sys/pull/229 cc @ianks

**Comment by ianks** [comment]
Hey @eregon so sorry I missed this until now. Working on making this happen -> https://github.com/oxidize-rb/rb-sys/pull/441
